{{- if and .Values.tensorrt.enabled (eq .Values.tensorrt.task "model-builder") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: tensorrt-model-builder
  namespace: tensorrt-llm-model-server
spec:
  template:
    spec:
      containers:
        - name: tensorrt-model-builder
          imagePullPolicy: Always
          image: {{ .Values.tensorrt.image_builder }}
          command: ["uv", "run", "main.py"]
          volumeMounts:
            - name: model-cache
              mountPath: /data
            - name: huggingface-token
              mountPath: /root/.cache/huggingface
              readOnly: true
            - name: gcp-service-account
              mountPath: /gcp/service-account.json
              subPath: service-account.json
              readOnly: true
          resources:
            requests:
              cpu: {{ .Values.tensorrt.requests.cpu }}
              memory: {{ .Values.tensorrt.requests.memory }}
              ephemeral-storage: 10Gi
              nvidia.com/gpu: "1"  # Request 1 GPU
            limits:
              cpu: {{ .Values.tensorrt.limits.cpu }}
              memory: {{ .Values.tensorrt.limits.memory }}
              nvidia.com/gpu: "1"  # Limit to 1 GPU
              ephemeral-storage: 20Gi
          env:
            - name: BUCKET_NAME
              value: "datascience-result-prod"
            - name: MODEL_NAME
              value: {{ .Values.tensorrt.model_name }}
            - name: ORGANIZATION
              value: {{ .Values.tensorrt.organization }}
            - name: HUGGINGFACE_HUB_CACHE
              value: "/data/hub"
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: huggingface-token
                  key: token
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/gcp/service-account.json"
      restartPolicy: Never
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: model-cache-pvc
        - name: huggingface-token
          secret:
            secretName: huggingface-token
            items:
              - key: token
                path: token
        - name: gcp-service-account
          secret:
            secretName: gcp-service-account
            items:
              - key: service-account.json
                path: service-account.json
      nodeSelector:
        cloud.google.com/gke-spot: "true"
        cloud.google.com/gke-accelerator: nvidia-l4
      terminationGracePeriodSeconds: 25
{{- end }}