{{- if .Values.tensorrt.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: tensorrt-service
  namespace: tensorrt-llm-model-server
  labels:
    app: tensorrt
spec:
  type: ClusterIP
  selector:
    app: tensorrt
  ports:
  - name: http
    port: 8000
    targetPort: http
  - name: grpc
    port: 8001
    targetPort: grpc
  - name: metrics
    port: 8002
    targetPort: metrics
{{- end }}
