{{- if .Values.tgi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: tgi-service
  namespace: tensorrt-llm-model-server
  labels:
    app: tgi
spec:
  type: ClusterIP
  selector:
    app: tgi
  ports:
  - name: http
    port: 8080
    targetPort: http
{{- end }}