apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: tensorrt-llm-model-server
  labels:
    app: prometheus
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
